# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Build environment
python:
  version: 3.12
  install:
    - requirements: docs/requirements.txt

# Sphinx documentation build
sphinx:
  configuration: docs/source/conf.py