from logicsimulator.model.Pin import Pin
from logicsimulator.viewmodel.PropagatorObject import PropagatorObject
from logicsimulator.core.idGenerator import generateId
import weakref

class PinVM(PropagatorObject):
    """View-model wrapper for a :class:`Pin`.

    ``PinVM`` exposes a pin’s properties and propagator signals to the UI
    layer. Each pin view-model has its own autogenerated ID and relays
    changes from the underlying :class:`Pin` instance through the
    :class:`PropagatorObject` mixin.
    """

    def __init__(self, parentId: str, pin: Pin):
        """Initialize the pin view-model.

        Args:
            parentId (str): ID of the component this pin belongs to.
            pin (Pin): The underlying model pin wrapped by this view-model.
        """
        self._parentId = parentId
        self._pin = weakref.ref(pin)
        self._id = generateId(prefix=self._pin().type)

        # ``PropagatorObject`` registers for propagator updates
        super().__init__(id=self._id, propagator=self._pin())

    @property
    def pin(self) -> Pin:
        """Pin: The underlying model pin."""
        return self._pin()

    @property
    def type(self) -> str:
        """str: Pin type (e.g., 'InputPin', 'OutputPin')."""
        return self.pin.type

    @property
    def id(self) -> str:
        """str: Unique auto-generated ID for this pin view-model."""
        return self._id

    @property
    def parentId(self) -> str:
        """str: ID of the parent component view-model."""
        return self._parentId